"""
HunterAI - Professional Report Generator
Generates vulnerability reports in PDF, HTML, Markdown, and DOCX formats.
AI-written narratives, evidence embedding, CVSS scoring, risk matrices.
"""

import os
import json
from datetime import datetime, timezone
from jinja2 import Template

from storage.local_store import LocalStore
from config import REPORTS_DIR, ASSETS_DIR

reports_store = LocalStore("reports")


# HTML Report Template
REPORT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - HunterAI Security Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', 'Segoe UI', sans-serif; background: #0a0e1a; color: #e0e0e0; padding: 40px; }
        .report-container { max-width: 1000px; margin: 0 auto; }
        .header { text-align: center; margin-bottom: 40px; padding: 40px; background: linear-gradient(135deg, #141825, #1a1f35); border-radius: 16px; border: 1px solid #2a2f45; }
        .header h1 { font-size: 28px; color: #ff2d55; margin-bottom: 8px; }
        .header .subtitle { color: #888; font-size: 14px; }
        .section { margin-bottom: 30px; }
        .section h2 { color: #00d4ff; font-size: 20px; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #2a2f45; }
        .finding-card { background: #141825; border-radius: 12px; padding: 24px; margin-bottom: 20px; border-left: 4px solid; }
        .finding-card.critical { border-color: #ff2d55; }
        .finding-card.high { border-color: #ff6b35; }
        .finding-card.medium { border-color: #ffb800; }
        .finding-card.low { border-color: #00d4ff; }
        .finding-card.info { border-color: #666; }
        .severity-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
        .severity-badge.critical { background: rgba(255,45,85,0.2); color: #ff2d55; }
        .severity-badge.high { background: rgba(255,107,53,0.2); color: #ff6b35; }
        .severity-badge.medium { background: rgba(255,184,0,0.2); color: #ffb800; }
        .severity-badge.low { background: rgba(0,212,255,0.2); color: #00d4ff; }
        .finding-title { font-size: 18px; font-weight: 600; margin: 12px 0 8px; }
        .evidence { background: #0a0e1a; border-radius: 8px; padding: 16px; margin: 12px 0; font-family: 'JetBrains Mono', monospace; font-size: 13px; overflow-x: auto; white-space: pre-wrap; }
        .meta-row { display: flex; gap: 20px; margin: 8px 0; font-size: 14px; color: #888; }
        .risk-matrix { width: 100%; border-collapse: collapse; margin: 16px 0; }
        .risk-matrix th, .risk-matrix td { padding: 12px; text-align: center; border: 1px solid #2a2f45; }
        .risk-matrix th { background: #1a1f35; color: #00d4ff; }
        .remediation { background: rgba(0,212,255,0.05); border: 1px solid rgba(0,212,255,0.2); border-radius: 8px; padding: 16px; margin: 12px 0; }
        .remediation h4 { color: #00d4ff; margin-bottom: 8px; }
        .footer { text-align: center; margin-top: 40px; padding: 20px; color: #555; font-size: 12px; }
    </style>
</head>
<body>
    <div class="report-container">
        <div class="header">
            <h1>🛡 {{ title }}</h1>
            <div class="subtitle">Generated by HunterAI | {{ date }} | {{ target }}</div>
        </div>

        <div class="section">
            <h2>Executive Summary</h2>
            <p>{{ executive_summary }}</p>
        </div>

        <div class="section">
            <h2>Risk Matrix</h2>
            <table class="risk-matrix">
                <tr><th>Severity</th><th>Count</th></tr>
                <tr><td><span class="severity-badge critical">Critical</span></td><td>{{ severity.critical }}</td></tr>
                <tr><td><span class="severity-badge high">High</span></td><td>{{ severity.high }}</td></tr>
                <tr><td><span class="severity-badge medium">Medium</span></td><td>{{ severity.medium }}</td></tr>
                <tr><td><span class="severity-badge low">Low</span></td><td>{{ severity.low }}</td></tr>
            </table>
        </div>

        <div class="section">
            <h2>Findings ({{ findings|length }})</h2>
            {% for finding in findings %}
            <div class="finding-card {{ finding.severity }}">
                <span class="severity-badge {{ finding.severity }}">{{ finding.severity }} | CVSS {{ finding.cvss_score }}</span>
                <div class="finding-title">{{ finding.name }}</div>
                <div class="meta-row">
                    <span>🔧 Tool: {{ finding.tool }}</span>
                    <span>🎯 Target: {{ finding.target_url }}</span>
                    <span>📋 {{ finding.cwe }}</span>
                </div>
                <p>{{ finding.description }}</p>
                {% if finding.evidence %}
                <div class="evidence">{{ finding.evidence }}</div>
                {% endif %}
                <div class="remediation">
                    <h4>Remediation</h4>
                    <p>{{ finding.remediation }}</p>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="footer">
            <p>HunterAI Security Report | Confidential | {{ date }}</p>
            <p>"Think Like a Hacker. Hunt Like a Machine."</p>
        </div>
    </div>
</body>
</html>
"""

# Markdown Report Template
REPORT_MD_TEMPLATE = """# 🛡 {{ title }}

**Generated by HunterAI** | {{ date }} | Target: {{ target }}

---

## Executive Summary

{{ executive_summary }}

---

## Risk Matrix

| Severity | Count |
|----------|-------|
| 🔴 Critical | {{ severity.critical }} |
| 🟠 High | {{ severity.high }} |
| 🟡 Medium | {{ severity.medium }} |
| 🔵 Low | {{ severity.low }} |
| **Total** | **{{ severity.total }}** |

---

## Findings

{% for finding in findings %}
### {{ loop.index }}. {{ finding.name }}

- **Severity**: {{ finding.severity | upper }} (CVSS {{ finding.cvss_score }})
- **Tool**: {{ finding.tool }}
- **Target**: {{ finding.target_url }}
- **CWE**: {{ finding.cwe }}

{{ finding.description }}

{% if finding.evidence %}
**Evidence:**
```
{{ finding.evidence }}
```
{% endif %}

**Remediation:** {{ finding.remediation }}

---

{% endfor %}

*Report generated by HunterAI — "Think Like a Hacker. Hunt Like a Machine."*
"""


class ReportGenerator:
    """Generates professional vulnerability reports."""

    def generate(self, hunt_id, title, target, findings, severity_summary, report_format="html"):
        """Generate a report in the specified format."""
        report_id = reports_store.generate_id()
        now = datetime.now(timezone.utc)

        # Build executive summary
        executive_summary = self._build_executive_summary(target, findings, severity_summary)

        context = {
            "title": title,
            "date": now.strftime("%B %d, %Y %H:%M UTC"),
            "target": target,
            "executive_summary": executive_summary,
            "findings": findings,
            "severity": severity_summary
        }

        # Generate report content
        if report_format == "html":
            content = Template(REPORT_HTML_TEMPLATE).render(**context)
            filename = f"report_{report_id}.html"
        elif report_format == "markdown":
            content = Template(REPORT_MD_TEMPLATE).render(**context)
            filename = f"report_{report_id}.md"
        else:
            content = Template(REPORT_HTML_TEMPLATE).render(**context)
            filename = f"report_{report_id}.html"

        # Save report file
        report_dir = os.path.join(REPORTS_DIR, hunt_id)
        os.makedirs(report_dir, exist_ok=True)
        report_path = os.path.join(report_dir, filename)

        with open(report_path, "w", encoding="utf-8") as f:
            f.write(content)

        # Save report metadata
        report_meta = {
            "report_id": report_id,
            "hunt_id": hunt_id,
            "title": title,
            "target": target,
            "format": report_format,
            "filename": filename,
            "file_path": report_path,
            "findings_count": len(findings),
            "severity_summary": severity_summary,
            "generated_at": now.isoformat()
        }
        reports_store.save(report_id, report_meta)

        return report_meta

    def _build_executive_summary(self, target, findings, severity):
        """Build an executive summary paragraph."""
        total = severity.get("total", 0)
        critical = severity.get("critical", 0)
        high = severity.get("high", 0)

        if total == 0:
            return f"A security assessment was conducted against {target}. No vulnerabilities were identified during this assessment."

        risk_level = "critical" if critical > 0 else "high" if high > 0 else "moderate"

        summary = (
            f"A comprehensive security assessment was conducted against {target}. "
            f"The assessment identified a total of {total} vulnerabilities: "
            f"{critical} Critical, {high} High, {severity.get('medium', 0)} Medium, "
            f"and {severity.get('low', 0)} Low severity findings. "
            f"The overall risk level is assessed as {risk_level.upper()}. "
        )

        if critical > 0:
            summary += "Immediate remediation of critical findings is strongly recommended before production deployment."
        elif high > 0:
            summary += "High-severity findings should be prioritized for remediation in the near term."

        return summary

    def get_report(self, report_id):
        """Get report metadata."""
        return reports_store.load(report_id)

    def list_reports(self, hunt_id=None):
        """List all reports."""
        reports = reports_store.list_all()
        if hunt_id:
            reports = [r for r in reports if r.get("hunt_id") == hunt_id]
        return reports

    def get_report_content(self, report_id):
        """Get the actual report file content."""
        meta = reports_store.load(report_id)
        if meta and os.path.exists(meta.get("file_path", "")):
            with open(meta["file_path"], "r", encoding="utf-8") as f:
                return f.read()
        return None


# Singleton
report_generator = ReportGenerator()
